version: '3.8'
services:

  db:
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: foodgram_backend

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    container_name: foodgram_frontend

  nginx:
    image: nginx:1.23.4
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - frontend
      - backend
    container_name: foodgram_nginx

volumes:
  static_volume:
  media_volume:
