version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    container_name: foodgram_db

  backend:
    image: olegisaev/foodgram_backend:latest
    restart: always
    volumes:
      - static_files:/app/static/
      - media_files:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    container_name: foodgram_backend

  frontend:
    image: olegisaev/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    container_name: foodgram_frontend

  nginx:
    image: nginx:1.23.4
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_files:/var/html/static/
      - media_files:/var/html/media/
    depends_on:
      - frontend
      - backend
    container_name: foodgram_nginx

volumes:
  static_files:
  media_files:
  postgres_data:
