# Generated by Django 3.2 on 2023-05-19 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeToIngredient', to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(through='recipes.RecipeToTag', to='recipes.Tag'),
        ),
        migrations.AddField(
            model_name='purchasetorecipes',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.purchases', verbose_name='Ссылка на покупку'),
        ),
        migrations.AddField(
            model_name='purchasetorecipes',
            name='reсipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Ссылка на рецепт'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='reсipes',
            field=models.ManyToManyField(through='recipes.PurchaseToRecipes', to='recipes.Recipe', verbose_name='Покупки'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='favoritetorecipes',
            name='favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.favorites', verbose_name='Ссылка на покупку'),
        ),
        migrations.AddField(
            model_name='favoritetorecipes',
            name='reсipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Ссылка на рецепт'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='favorites',
            field=models.ManyToManyField(through='recipes.FavoriteToRecipes', to='recipes.Recipe', verbose_name='Покупки'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
